<h1>Basic Form</h1>
<form action="/?c=example&amp;a=form_raw" method="post" accept-charset="utf-8">
  <table border="1" cellspacing="5" cellpadding="5">
    <tr>
      <th>Name:</th>
      <td><input type="text" name="name" value="foo">*</td>
    </tr>
    <tr>
      <th>PHP:</th>
      <td>
        <select name="php">
          <option value="rocks">Rocks</option>
          <option value="sucks">Sucks</option>
        </select>
      </td>
    </tr>
  </table>
  
  <p><input type="submit" value="Post Form"></p>
</form>
<hr />
<h1>Results</h1>
<div class="indent">
  <b>Post Data</b>
  <pre><?= var_dump($_POST) ?></pre>
  <b>Is it a post?</b>
  <pre><?= $is_it_a_post ?></pre>
</div>