<h2>Itsy Examples</h2>
<h3>The Basics</h3>
<p>
  <ul>
    <li><a href="/?c=example&amp;a=index">This page</a></li>
    <li><a href="/?c=example&amp;a=form_raw">Basic form; raw data.</a></li>
    <li><a href="/?c=example&amp;a=form_request">Basic form; using request class.</a></li>
    <li><a href="/?c=example&amp;a=form_error">Basic form; with error checking.</a></li>
    <li><a href="/?c=example&amp;a=flash">Flash messages</a></li>
  </ul>
</p>
