<?php

class test_itsy_dispatch extends PHPUnit_Framework_TestCase
{
  public function test_successful_internal_action()
  {
    ob_start();
      itsy::dispatch('itsy_error', '_error503');
      $content = ob_get_contents();
    ob_end_clean();
    
    $find = '503 - Service Unavailable';
    if (strpos($content, $find) === false) {
      $this->fail("Unable to find '503 - Service Unavailable' in the content.");
    }
  }
  
  public function test_unsuccessful_internal_action()
  {
    try {
      ob_start();
        itsy::dispatch('test', '_internal', null, false, true);
      ob_end_clean();
    } catch (itsy_exception $e) {
      $this->assertEquals('Access Denied to internal action.', $e->getMessage());
    }
  }
  
  public function test_forward_directive()
  {
    ob_start();
      itsy::dispatch('test', 'forward');
      $content = ob_get_contents();
    ob_end_clean();
    
    $find = 'this is to test the forward directive; do not edit this file.';
    $this->assertEquals($find, $content);
  }
  
  public function test_partial()
  {
    $content = itsy::partial('test', '_partial');
    
    $find = 'this is a test partial; do not edit this file.';
    $this->assertEquals($find, $content);
  }
  
  public function test_no_layout()
  {
    ob_start();
      itsy::dispatch('test', 'no_layout');
      $content = ob_get_contents();
    ob_end_clean();
    
    $find = 'this is to test no layout; do not edit this file';
    $this->assertEquals($find, $content);
  }
}

?>